In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD 
from sklearn.utils import shuffle

Using TensorFlow backend.


# Parameter

In [2]:
M = 2     # 입력 데이터의 차원
K = 3      # 클래스 수
n = 100  # 각 클래스에 있는 데이터 수
N = n*K  # 전체 데이터 수

# Data

In [5]:
np.random.seed(20181222)

X1 = np.random.randn(n, M) + np.array([0, 10])
X2 = np.random.randn(n, M) + np.array([5, 5])
X3 = np.random.randn(n, M) + np.array([10, 0])

Y1 = np.array([[1,0,0] for i in range(n)])
Y2 = np.array([[0,1,0] for i in range(n)])
Y3 = np.array([[0,0,1] for i in range(n)])

X = np.concatenate((X1, X2, X3), axis=0)
Y = np.concatenate((Y1, Y2, Y3), axis=0)

# Model

In [4]:
model = Sequential([ Dense(input_dim=M, units=K), Activation('softmax')])
model.compile(loss='categorical_crossentropy', optimizer=SGD(lr=0.1))

# Training

In [6]:
# training
model.fit(X, Y, epochs=300, batch_size=50)

Epoch 1/300
300/300 [==============================] - 0s 561us/step - loss: 1.4227
Epoch 2/300
300/300 [==============================] - 0s 24us/step - loss: 0.2346
Epoch 3/300
300/300 [==============================] - 0s 23us/step - loss: 0.1591
Epoch 4/300
300/300 [==============================] - 0s 35us/step - loss: 0.1188
Epoch 5/300
300/300 [==============================] - 0s 27us/step - loss: 0.0981
Epoch 6/300
300/300 [==============================] - 0s 36us/step - loss: 0.0841
Epoch 7/300
300/300 [==============================] - 0s 28us/step - loss: 0.0745
Epoch 8/300
300/300 [==============================] - 0s 29us/step - loss: 0.0675
Epoch 9/300
300/300 [==============================] - 0s 28us/step - loss: 0.0616
Epoch 10/300
300/300 [==============================] - 0s 21us/step - loss: 0.0572
Epoch 11/300
300/300 [==============================] - 0s 27us/step - loss: 0.0538
Epoch 12/300
300/300 [==============================] - 0s 24us/step - loss: 0.0497


300/300 [==============================] - 0s 24us/step - loss: 0.0143
Epoch 99/300
300/300 [==============================] - 0s 25us/step - loss: 0.0142
Epoch 100/300
300/300 [==============================] - 0s 25us/step - loss: 0.0142
Epoch 101/300
300/300 [==============================] - 0s 33us/step - loss: 0.0141
Epoch 102/300
300/300 [==============================] - 0s 23us/step - loss: 0.0140
Epoch 103/300
300/300 [==============================] - 0s 25us/step - loss: 0.0139
Epoch 104/300
300/300 [==============================] - 0s 26us/step - loss: 0.0139
Epoch 105/300
300/300 [==============================] - 0s 27us/step - loss: 0.0139
Epoch 106/300
300/300 [==============================] - 0s 25us/step - loss: 0.0137
Epoch 107/300
300/300 [==============================] - 0s 25us/step - loss: 0.0137
Epoch 108/300
300/300 [==============================] - 0s 26us/step - loss: 0.0136
Epoch 109/300
300/300 [==============================] - 0s 24us/step - loss: 0.

300/300 [==============================] - 0s 25us/step - loss: 0.0103
Epoch 195/300
300/300 [==============================] - 0s 28us/step - loss: 0.0102
Epoch 196/300
300/300 [==============================] - 0s 21us/step - loss: 0.0102
Epoch 197/300
300/300 [==============================] - 0s 28us/step - loss: 0.0102
Epoch 198/300
300/300 [==============================] - 0s 22us/step - loss: 0.0102
Epoch 199/300
300/300 [==============================] - 0s 23us/step - loss: 0.0102
Epoch 200/300
300/300 [==============================] - 0s 26us/step - loss: 0.0101
Epoch 201/300
300/300 [==============================] - 0s 24us/step - loss: 0.0100
Epoch 202/300
300/300 [==============================] - 0s 24us/step - loss: 0.0100
Epoch 203/300
300/300 [==============================] - 0s 19us/step - loss: 0.0100
Epoch 204/300
300/300 [==============================] - 0s 28us/step - loss: 0.0101
Epoch 205/300
300/300 [==============================] - 0s 22us/step - loss: 0

300/300 [==============================] - 0s 24us/step - loss: 0.0084
Epoch 291/300
300/300 [==============================] - 0s 24us/step - loss: 0.0085
Epoch 292/300
300/300 [==============================] - 0s 23us/step - loss: 0.0083
Epoch 293/300
300/300 [==============================] - 0s 23us/step - loss: 0.0084
Epoch 294/300
300/300 [==============================] - 0s 26us/step - loss: 0.0083
Epoch 295/300
300/300 [==============================] - 0s 29us/step - loss: 0.0083
Epoch 296/300
300/300 [==============================] - 0s 29us/step - loss: 0.0083
Epoch 297/300
300/300 [==============================] - 0s 25us/step - loss: 0.0082
Epoch 298/300
300/300 [==============================] - 0s 25us/step - loss: 0.0082
Epoch 299/300
300/300 [==============================] - 0s 21us/step - loss: 0.0083
Epoch 300/300
300/300 [==============================] - 0s 22us/step - loss: 0.0083


# Result

In [12]:
X_, Y_ = shuffle(X, Y)
classes = model.predict_classes(X_[0:10], batch_size=1)
prob     = model.predict_proba(X_[0:10], batch_size=1)

print('classified:')
print(np.argmax(Y_[0:10], axis=1) == classes)
print()
print('output probability:')
print(prob)

classified:
[ True  True  True  True  True  True  True  True  True  True]

output probability:
[[1.2364044e-14 2.7588524e-03 9.9724114e-01]
 [1.1798830e-15 4.4003414e-04 9.9955994e-01]
 [9.9997509e-01 2.4909845e-05 1.5313494e-15]
 [2.0910476e-03 9.9780947e-01 9.9516838e-05]
 [5.2394539e-06 9.9760807e-01 2.3866766e-03]
 [2.3646033e-03 9.9745828e-01 1.7713608e-04]
 [9.9999750e-01 2.4579260e-06 1.4031707e-16]
 [2.3837052e-17 1.0534122e-05 9.9998951e-01]
 [4.8703429e-22 9.9647394e-08 9.9999988e-01]
 [9.9617946e-01 3.8204961e-03 8.2086317e-12]]


(10,)